[Definition]
failregex = ^<HOST> .*"(GET|POST|HEAD|PUT|OPTIONS|DELETE) /\S*(wp-login\.php|wp-admin|\.env|\.git|actuator|config\.json|phpmyadmin|adminer|server-status|\.aws|\.bak|\.sql|shell\.php|c99|r57|\.htaccess|xmlrpc\.php)
ignoreregex =
